# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_auto_20170907_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='pin',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='date_applied',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pin',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pin_application', to='admission.Application'),
        ),
    ]
