# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_auto_20170907_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='session',
        ),
    ]
