# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_application_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cert1_img',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='application',
            name='cert2_img',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='application',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='application',
            name='programme',
            field=models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate'), ('Degree Foundation', 'Degree Foundation')], max_length=50),
        ),
    ]
