# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_auto_20170907_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='jamb_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='jamb_score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
