# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_auto_20170907_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='lga',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
