# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_application_lga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cert1',
            field=models.CharField(blank=True, choices=[('WAEC', 'WAEC'), ('NECO', 'NECO'), ('NABTEB', 'NABTEB'), ("A'Levels", "A'Levels"), ('IJMB', 'IJMB'), ('JUPEB', 'JUPEB'), ('NCE', 'NCE'), ('ND', 'ND'), ('HND', 'HND')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='cert2',
            field=models.CharField(blank=True, choices=[('WAEC', 'WAEC'), ('NECO', 'NECO'), ('NABTEB', 'NABTEB'), ("A'Levels", "A'Levels"), ('IJMB', 'IJMB'), ('JUPEB', 'JUPEB'), ('NCE', 'NCE'), ('ND', 'ND'), ('HND', 'HND')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='pin',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='programme_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Transfer', 'Transfer'), ('Direct Entry', 'Direct Entry')], max_length=50),
        ),
    ]
