# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0010_auto_20170907_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='offence_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
