# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0011_auto_20170907_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cert1_subject',
        ),
        migrations.AddField(
            model_name='application',
            name='cert1_subject',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='application',
            name='cert2_subject',
        ),
        migrations.AddField(
            model_name='application',
            name='cert2_subject',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='first_choice',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='second_choice',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
