# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-09 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0013_auto_20170908_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='degree_img',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='application',
            name='type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=50),
        ),
    ]
