# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-10 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0015_auto_20170910_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='programme',
            field=models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate'), ('JUPEB', 'JUPEB')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='programme_type',
            field=models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=50, null=True),
        ),
    ]
