# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-15 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0017_auto_20170913_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='dateBirth',
            field=models.DateField(),
        ),
    ]
