# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-19 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0018_auto_20170915_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='dateBirth',
            new_name='date_birth',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='stateOrigin',
            new_name='state_of_origin',
        ),
    ]
