# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-24 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0020_auto_20170924_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='transcript_img',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='application',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='session.Session'),
        ),
    ]
