# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-26 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0001_initial'),
        ('admission', '0021_auto_20170924_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='major.Major'),
        ),
    ]
