# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-17 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0024_auto_20170928_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='jamb_no',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
