# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-20 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0025_auto_20171017_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='next_kin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='sponsor',
            field=models.TextField(),
        ),
    ]
