# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-23 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0026_auto_20180720_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='curr_cgpa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='reason_transfer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='programme',
            field=models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Undergraduate Transfer', 'Undergraduate Transfer'), ('Postgraduate', 'Postgraduate'), ('JUPEB', 'JUPEB')], max_length=200),
        ),
    ]
