# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-25 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0027_auto_20180723_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_no',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
