# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-28 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0028_application_app_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='curr_course',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='curr_uni',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='curr_year_of_entry',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='email_dean',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='email_hod',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
