# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-27 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0030_auto_20180907_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='mode_of_entry',
            field=models.CharField(blank=True, choices=[('UTME Candidate', 'UTME Candidate'), ('Transfer', 'Transfer'), ('Direct Entry', 'Direct Entry'), ('Conversion', 'Conversion')], max_length=200, null=True),
        ),
    ]
