# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-07 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0031_auto_20190227_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='sponsor_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
