# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-04-04 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0032_application_sponsor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cert1',
            field=models.CharField(blank=True, choices=[('WAEC', 'WAEC'), ('NECO', 'NECO'), ('NABTEB', 'NABTEB'), ("A'Levels", "A'Levels"), ('NBAIS', 'NBAIS'), ('GCE "A"', 'GCE "A"'), ('IJMB', 'IJMB'), ('JUPEB', 'JUPEB')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='cert2',
            field=models.CharField(blank=True, choices=[('WAEC', 'WAEC'), ('NECO', 'NECO'), ('NABTEB', 'NABTEB'), ("A'Levels", "A'Levels"), ('NBAIS', 'NBAIS'), ('GCE "A"', 'GCE "A"'), ('IJMB', 'IJMB'), ('JUPEB', 'JUPEB')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='degree',
            field=models.CharField(blank=True, choices=[('IJMB', 'IJMB'), ('JUPEB', 'JUPEB'), ('NCE', 'NCE'), ('ND', 'ND'), ('HND', 'HND'), ('FIRST DEGREE', 'FIRST DEGREE')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='programme',
            field=models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Undergraduate Transfer', 'Undergraduate Transfer'), ('Postgraduate', 'Postgraduate'), ('JUPEB', 'JUPEB'), ('NBAIS', 'NBAIS')], max_length=200),
        ),
    ]
