# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-04-07 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0033_auto_20190404_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='arabic_cert',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='arabic_cert_img',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
