# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-08-09 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0035_auto_20190423_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='find_out',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
