# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-08-14 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0036_application_find_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='lga',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='nationality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='state_of_origin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
