# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-02 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nysc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('matric_no', models.CharField(max_length=200)),
                ('jamb_no', models.CharField(max_length=200)),
                ('date_birth', models.DateField()),
                ('state_origin', models.CharField(max_length=200)),
                ('marital_status', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=200)),
                ('programme', models.CharField(max_length=200)),
                ('programme_type', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('parent_no', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=255)),
                ('date', models.DateTimeField()),
                ('img', models.ImageField(blank=True, null=True, upload_to=b'')),
            ],
        ),
    ]
