# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nysc',
            name='middle_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
