# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-13 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0002_nysc_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nysc',
            name='matric_no',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
