# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-08 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('level', '0001_initial'),
        ('dept', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('Compulsory', 'Compulsory'), ('Elective', 'Elective'), ('Required', 'Required')], max_length=20)),
                ('ca', models.IntegerField(default=30)),
                ('exam', models.IntegerField(default=70)),
                ('semester', models.IntegerField(choices=[(1, '1st Semester'), (2, '2nd Semester')], default=0)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept.Dept')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='level.Level')),
            ],
        ),
    ]
