# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20170624_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ca',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='course',
            name='exam',
            field=models.IntegerField(default=70),
        ),
    ]
