# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-08 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('merchant_id', models.CharField(blank=True, max_length=256, null=True)),
                ('service_type_id', models.CharField(blank=True, max_length=256, null=True)),
                ('api_key', models.CharField(blank=True, max_length=256, null=True)),
                ('public_key', models.CharField(blank=True, max_length=256, null=True)),
                ('private_key', models.CharField(blank=True, max_length=256, null=True)),
                ('code', models.CharField(blank=True, max_length=256, null=True)),
                ('admission', models.BooleanField(default=False)),
                ('incur_charges', models.BooleanField(default=True)),
            ],
        ),
    ]
