# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-25 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymenttype', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='api_key',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='merchant_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='service_type_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
