# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-16 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0002_auto_20181026_0752'),
        ('paymenttype', '0002_tuitionfee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuitionfee',
            name='dept',
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Both', 'Both')], default='Both', max_length=256),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='tuition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tuitionfee',
            name='conversion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tuitionfee',
            name='de',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tuitionfee',
            name='jme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tuitionfee',
            name='major',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='major.Major'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tuitionfee',
            name='pt',
            field=models.BooleanField(default=False),
        ),
    ]
