# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-21 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymenttype', '0003_auto_20171206_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
