# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-26 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymenttype', '0004_paymenttype_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='admission',
            field=models.BooleanField(default=False),
        ),
    ]
