# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-04 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymenttype', '0005_paymenttype_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='incur_charges',
            field=models.BooleanField(default=True),
        ),
    ]
