# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-14 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymenttype', '0007_tuitionfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Both', 'Both')], default='Both', max_length=256),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='tuition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tuitionfee',
            name='conversion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tuitionfee',
            name='de',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tuitionfee',
            name='jme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tuitionfee',
            name='pt',
            field=models.BooleanField(default=False),
        ),
    ]
