# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-03 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymenttype', '0009_auto_20181114_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitionfee',
            name='ft',
            field=models.BooleanField(default=True),
        ),
    ]
