# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-17 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymenttype', '0010_tuitionfee_ft'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='tag',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
