# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-08 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0001_initial'),
        ('session', '0001_initial'),
        ('transcript', '0001_initial'),
        ('accounts', '0001_initial'),
        ('paymenttype', '0001_initial'),
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Web', 'Web'), ('eCashier', 'eCashier')], default='Web', max_length=256)),
                ('transaction_id', models.CharField(blank=True, max_length=256, null=True)),
                ('order_id', models.CharField(blank=True, max_length=256, null=True)),
                ('prn', models.TextField(blank=True, null=True)),
                ('rrr', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.Application')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='level.Level')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymenttype.PaymentType')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='session.Session')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
                ('transcript_app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcript_app', to='transcript.Application')),
            ],
        ),
    ]
