# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-26 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20170926_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(max_length=256),
        ),
    ]
