# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-26 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20170926_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
