# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-18 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20171206_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='rrr',
            new_name='prn',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('Web', 'Web'), ('eCashier', 'eCashier')], default='Web', max_length=256),
        ),
    ]
