# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-26 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
        ('payment', '0008_auto_20180218_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='level.Level'),
        ),
    ]
