# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-25 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_payment_rrr'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
