# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-28 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0004_application_region_detail'),
        ('payment', '0012_payment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transcript_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcript_app', to='transcript.Application'),
        ),
    ]
