# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_session_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_admission',
            field=models.BooleanField(default='0'),
        ),
    ]
