# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-26 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
