from accounts.models.unit import Unit
from accounts.models.user import User
from accounts.models.college_officer import CollegeOfficer
from accounts.models.academic_affairs import AcademicAffairs
from accounts.models.bursar import Bursar
from accounts.models.dean import Dean
from accounts.models.lecturer import Lecturer
from accounts.models.student import Student
from accounts.models.student_affairs import StudentAffairs
