# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-12 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5)),
                ('lower_limit', models.FloatField()),
                ('upper_limit', models.FloatField()),
                ('gp', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
