# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-17 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=255)),
                ('lower_limit', models.FloatField()),
                ('upper_limit', models.FloatField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
