# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-23 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='acronym',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
