# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('level', '0001_initial'),
        ('major', '0001_initial'),
        ('paymenttype', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentToMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='level.Level')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='major.Major')),
                ('paymenttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymenttype.PaymentType')),
            ],
        ),
    ]
