# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-21 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymenttomajor', '0003_auto_20170919_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttomajor',
            name='conversion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymenttomajor',
            name='de',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymenttomajor',
            name='jme',
            field=models.BooleanField(default=False),
        ),
    ]
