# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-03 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymenttomajor', '0005_paymenttomajor_pt'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttomajor',
            name='ft',
            field=models.BooleanField(default=True),
        ),
    ]
