# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-08 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session', '0001_initial'),
        ('accounts', '0001_initial'),
        ('dept', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseResultGPA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('tcp', models.FloatField()),
                ('tnu', models.FloatField()),
                ('gpa', models.FloatField()),
                ('ctcp', models.FloatField()),
                ('ctnu', models.FloatField()),
                ('cgpa', models.FloatField()),
                ('tce', models.FloatField()),
                ('prev_ctcp', models.FloatField()),
                ('prev_ctnu', models.FloatField()),
                ('prev_cgpa', models.FloatField()),
                ('prev_tce', models.FloatField()),
                ('status', models.IntegerField()),
                ('rel', models.BooleanField(default=0)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept.Dept')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.Session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='courseresultgpa',
            unique_together=set([('student', 'session', 'semester')]),
        ),
    ]
