# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-23 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_student_parent_email'),
        ('session', '0003_session_is_admission'),
        ('courseresultgpa', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseresultgpa',
            unique_together=set([('student', 'session', 'semester')]),
        ),
    ]
