# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-18 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseresult', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
