# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-13 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
        ('courseresult', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseresult',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='level.Level'),
        ),
    ]
