# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-21 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20171002_1433'),
        ('accounts', '0020_student_edit'),
        ('session', '0003_session_is_admission'),
        ('courseresult', '0002_releasestatus'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseresult',
            unique_together=set([('course', 'student', 'session')]),
        ),
    ]
