# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-07 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseresult', '0004_courseresult_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca', models.BooleanField(default=False)),
                ('exam', models.BooleanField(default=False)),
            ],
        ),
    ]
