# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170619_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Normal'), ('2', 'Exchange'), ('3', 'Leave'), ('4', 'Sick'), ('5', 'Suspension'), ('6', 'Withdrawn')], default='1', max_length=15),
        ),
    ]
