# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170619_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeofficer',
            name='college',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college.College'),
        ),
    ]
