# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 12:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
        ('accounts', '0007_auto_20170725_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college.College')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Normal'), ('2', 'Exchange'), ('3', 'Leave'), ('4', 'Sick'), ('5', 'Suspension'), ('6', 'Deferment'), ('7', 'Withdrawn'), ('8', 'Graduated')], default='1', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Academic Affairs'), ('3', 'Bursar'), ('4', 'Student Affairs'), ('5', 'College Officer'), ('6', 'Lecturer'), ('7', 'Student'), ('8', 'Dean')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='dean',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
