# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-13 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170910_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
