# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170913_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='cv',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
