# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20170916_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='modeOfEntry',
            new_name='mode_of_entry',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='oLevel',
            new_name='olevel',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='parentNo',
            new_name='parent_no',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='bloodGroup',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dateBirth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='genotype',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lga',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nextKin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nextKinAddress',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stateOrigin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='town',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_birth',
            field=models.DateField(default='1970-01-01', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='genotype',
            field=models.CharField(blank=True, choices=[('AA', 'AA'), ('AS', 'AS'), ('SS', 'SS'), ('CS', 'CS')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lga',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='next_kin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='next_kin_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='religion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state_origin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='town',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
