# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20170916_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='img',
        ),
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
