# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-19 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20170916_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='rank',
            field=models.CharField(blank=True, choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Senior Lecturer', 'Senior Lecturer'), ('Lecturer I', 'Lecturer I'), ('Lecturer II', 'Lecturer II'), ('Assistant Lecturer', 'Assistant Lecturer'), ('Graduate Assistant', 'Graduate Assistant'), ('Contract', 'Contract')], max_length=20, null=True),
        ),
    ]
