# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-02 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20170919_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rank',
            field=models.CharField(blank=True, choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Senior Lecturer', 'Senior Lecturer'), ('Lecturer I', 'Lecturer I'), ('Lecturer II', 'Lecturer II'), ('Assistant Lecturer', 'Assistant Lecturer'), ('Graduate Assistant', 'Graduate Assistant')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='status',
            field=models.CharField(blank=True, choices=[('Permanent', 'Permanent'), ('Adjunct', 'Adjunct'), ('Contract', 'Contract')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Unit'),
        ),
    ]
