# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-02 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20171002_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rank',
            new_name='profile_rank',
        ),
    ]
