# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-02 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20180120_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='edit',
            field=models.BooleanField(default=False),
        ),
    ]
