# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-12 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20180707_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='olevel',
            field=models.CharField(blank=True, choices=[('WAEC', 'WAEC'), ('NECO', 'NECO'), ('WAEC/GCE', 'WAEC/GCE'), ('NECO/GCE', 'NECO/GCE'), ('WAEC/NECO', 'WAEC/NECO'), ('NABTEB', 'NABTEB'), ('NABTEB/WAEC', 'NABTEB/WAEC'), ('NABTEB/NECO', 'NABTEB/NECO'), ('NABTEB/GCE', 'NABTEB/GCE')], max_length=15, null=True),
        ),
    ]
