# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-06 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20180712_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sign',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
