# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-30 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_user_mail_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
