# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-30 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20190130_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lga',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='state_origin',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
