# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hod',
            name='dept',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dept.Dept'),
        ),
        migrations.AlterField(
            model_name='hod',
            name='lecturer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Lecturer'),
        ),
    ]
