# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-19 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latereg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='approvedBy',
            new_name='approved_by',
        ),
    ]
