# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dept', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('tcg', models.IntegerField(default='')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept.Dept')),
            ],
        ),
    ]
