# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-20 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='matric_no',
        ),
    ]
