# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-17 12:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session', '0003_session_is_admission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('major', '0002_auto_20181023_0736'),
        ('accounts', '0026_user_mail_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntraUni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('paid', models.BooleanField(default=False)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='major.Major')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.Session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
            ],
        ),
    ]
