# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-29 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0006_auto_20181023_0736'),
        ('session', '0003_session_is_admission'),
        ('accounts', '0024_auto_20180712_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('upload_type', models.TextField()),
                ('uploaded', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_upload_lecturer', to='accounts.Lecturer')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.Session')),
            ],
        ),
    ]
