# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseallocation', '0003_auto_20170626_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseallocation',
            name='assisting',
        ),
        migrations.RemoveField(
            model_name='courseallocation',
            name='coordinator',
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='position',
            field=models.IntegerField(choices=[(1, 'Coordinator'), (2, 'Assisting')], default=2),
        ),
    ]
