# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-19 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20170919_0849'),
        ('courseallocation', '0004_auto_20170626_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseallocation',
            name='allocatedBy',
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='allocated_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='allocated_by', to='accounts.Lecturer'),
            preserve_default=False,
        ),
    ]
