# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-19 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursewaving', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wavedcourses',
            old_name='wavedBy',
            new_name='waved_by',
        ),
    ]
