# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-05 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20171002_1433'),
        ('accounts', '0020_student_edit'),
        ('coursewaving', '0002_auto_20170919_1233'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wavedcourses',
            unique_together=set([('course', 'student')]),
        ),
    ]
