# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_auto_20170614_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseToMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Course')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Level')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Major')),
            ],
        ),
    ]
