# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
        ('accounts', '0006_auto_20170624_1138'),
        ('session', '0001_initial'),
        ('course', '0003_auto_20170624_0927'),
        ('coursereg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='level.Level')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.Session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='courseregister',
            name='course',
        ),
        migrations.DeleteModel(
            name='CourseRegister',
        ),
    ]
