# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-17 12:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_session_is_admission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0026_user_mail_prefix'),
        ('coursereg', '0003_auto_20180504_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraUnitRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('status', models.IntegerField()),
                ('units', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.Session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
            ],
        ),
    ]
