# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-29 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymentwaving', '0004_wavedpayment_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wavedpayment',
            name='waved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Bursar'),
        ),
    ]
