# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-14 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymentwaving', '0005_auto_20181029_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wavedpayment',
            name='waved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Bursar'),
        ),
    ]
