# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-08 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dept', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('matric_no', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('date_birth', models.DateField()),
                ('phone', models.CharField(max_length=255)),
                ('nationality', models.TextField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255)),
                ('mode_of_entry', models.CharField(max_length=255)),
                ('year_admission', models.CharField(max_length=255)),
                ('year_graduation', models.CharField(blank=True, max_length=255, null=True)),
                ('student_status', models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate')], max_length=255)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('degree_date', models.DateField(blank=True, null=True)),
                ('purpose', models.TextField()),
                ('address_to', models.TextField()),
                ('region', models.TextField(choices=[('Local', 'Local'), ('Foreign', 'Foreign')], default='Local')),
                ('region_detail', models.TextField(blank=True, choices=[('Africa', 'Africa'), ('North America', 'North America'), ('South America', 'South America'), ('Europe', 'Europe'), ('Asia', 'Asia'), ('Oceania', 'Oceania')], null=True)),
                ('request_type', models.CharField(choices=[('Fresh Request', 'Fresh Request'), ('Reprint', 'Reprint')], max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('date_applied', models.DateTimeField()),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept.Dept')),
            ],
        ),
    ]
