# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-07 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0004_application_region_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='label',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='application',
            name='reason_denial',
            field=models.TextField(blank=True, null=True),
        ),
    ]
