# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('level', '0001_initial'),
        ('accounts', '0006_auto_20170624_1138'),
        ('major', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelAdviser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Lecturer')),
                ('level', models.ManyToManyField(to='level.Level')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='major.Major')),
            ],
        ),
    ]
