# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-18 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leveladviser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leveladviser',
            name='lecturer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Lecturer'),
        ),
    ]
